services:
  - type: web
    name: movie-recs-api
    env: python
    rootDir: backend
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-recs-db
          property: connectionString
      - key: TMDB_API_KEY
        fromSecret:
          name: TMDB_API_KEY
      - key: POPULARITY_CSV_PATH
        value: /tmp/top_movies.csv
    regions:
      - oregon

  - type: web
    name: movie-recs-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p 3000
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://movie-recs-api.onrender.com
    regions:
      - oregon

databases:
  - name: movie-recs-db
    plan: free

