services:
  - type: web
    name: movie-recs-api
    env: docker
    rootDir: backend
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/data
      sizeGB: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-recs-db
          property: connectionString
      - key: POPULARITY_CSV_PATH
        value: /opt/data/top_movies.csv
    regions:
      - oregon

  - type: web
    name: movie-recs-frontend
    env: node
    rootDir: frontend
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p 3000
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://movie-recs-api.onrender.com
    regions:
      - oregon

databases:
  - name: movie-recs-db
    plan: free

cronJobs:
  - name: train-popularity-daily
    schedule: "0 3 * * *"
    command: bash -lc "cd backend && pip install -r requirements.txt && POPULARITY_CSV_PATH=/opt/data/top_movies.csv python scripts/train_popularity.py"
    env: docker

